books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list/',views.book_list,name='list'),
    path('book/create/<int:pk>/',views.book_detail,name='detail'),
    path('book/add/',views.add_book,name='add_book'),
    path('book/update/<int:pk>/', views.update_book, name='update'),
    path('book/delete/<int:pk>/', views.delete_book, name='delete'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('',include('users.urls'))
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('',views.register_view,name='register'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
]

books/models.py
from django.db import models
from django.utils import timezone

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    published_at = models.DateField(default=timezone.now)
    author_name = models.CharField(max_length=200)

    class Meta:
        ordering = ['-published_at']

users/models.py
from django.db import models

books/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title','description','author_name','published_at')
        widgets = {
            'title':forms.TextInput(attrs={
                'class':'form-control'
            }),
            'description': forms.Textarea(attrs={
                'class':'form-control'
            }),
            'author_name': forms.TextInput(attrs={
                'class':'form-control'
            }),
            'published_at': forms.DateInput(attrs={
                'class': 'form-control'
            })

        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password


class RegisterForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        super(UserCreationForm,self).__init__(*args,**kwargs)
        self.fields['username'].help_text = None

    password1 = forms.CharField(
        label = "Parol kiriting",
        widget = forms.PasswordInput(
            attrs={'class':'form-control'}
        ),
        validators=[validate_password]
    )
    password2 = forms.CharField(
        label="Parolni tasdiqlang",
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        ),
        validators=[validate_password]
    )
    class Meta:
        model = User
        fields = ('username','email')
        widgets = {
            'username': forms.TextInput(
            attrs={'class':'form-control'}
        ),
            'email': forms.EmailInput(
            attrs={'class':'form-control'}
        )
        }
class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=25,
        label='Foydalanuvchi nomi:',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label='Parolingizni kiriting:',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

books/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book
from .forms import BookForm


@login_required
def book_list(request):
    books = Book.objects.all()
    return render(request, 'book_list.html', {'books': books})


@login_required
def book_detail(request, pk):
    book = Book.objects.get(pk=pk)
    return render(request, 'book_detail.html', {'book': book})


@login_required
def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('list')
        else:
            return HttpResponse("Form is invalid")
    form = BookForm()
    return render(request, 'add_book.html', {'form': form})


@login_required
def update_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('detail', pk=pk)
        else:
            return HttpResponse("Form is invalid")
    form = BookForm(instance=book)
    return render(request, 'add_book.html', {'form': form, 'book': book})


@login_required
def delete_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect('list')
    return render(request, 'confirm.html', {'book': book})

users/views.py
from django.contrib.auth import authenticate, login,logout
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm


def register_view(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    form = RegisterForm()
    return render(request,'register.html',{'form':form})
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                              username=cd['username'],
                              password=cd['password'])
            if user is not None:
                login(request, user)
                return redirect('list')
    form = LoginForm()
    return render(request,'login.html',{'form':form})

def logout_view(request):
    logout(request)
    return redirect('users:login')

templates/add_book.html
{% extends 'base.html' %}
{% block title %}{% if book %}Update Book{% else %} Add Book {% endif %}{% endblock %}
{% block content%}
    <h1>{% if book %}Update Book{% else %} Add Book {% endif %}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body>

    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <footer>
        <p>Powered by <a href="https://www.linkedin.com/in/zuhra-erkayeva/">Erkayeva Zuhra</a></p>
    </footer>
    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/book_detail.html
{% extends 'base.html' %}
{% block title %}{{book.title}}{% endblock %}
{% block content%}
    <h1>{{book.title}}</h1>
    <p>{{ book.description }}</p>
    <p><strong>Author:</strong> {{book.author_name}}</p>
    <p><strong>Publication Date:</strong> {{book.published_at}}</p>
    <a href="{% url 'list' %}" class="btn btn-primary back-link">Back</a>
{% endblock %}

templates/book_list.html
{% extends 'base.html' %}

{% block title %}Library{% endblock %}

{% block content %}
<h1>Library</h1>
<a class="btn btn-primary" href="{% url 'users:logout' %}" role="button" style="margin-left:90%">Logout</a>
<a href="{% url 'add_book' %}" class="btn btn-primary add-book">Add Book</a>
<ol>
    {%for book in books%}
    <li>
        <span class="book-title"><a href="{% url 'detail' pk=book.pk %}">{{ book.title }}</a></span>
        <a href="{% url 'delete' pk=book.pk %}"><i class="bi bi-trash-fill"></i></a>
        <a href="{% url 'update' pk=book.pk %}"><i class="bi bi-pencil-square"></i></a>
    </li>
    {% endfor %}

</ol>
{% endblock %}

templates/confirm.html
{% extends 'base.html' %}
{% block title%}Library{% endblock %}

{% block content %}
    <h1>Are you to delete this  {{ book.title }}</h1>
    <div class="btn-container">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes</button>
        </form>
        <a href="{% url 'list' %}" class="btn btn-secondary">No</a>
        </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kirish</title>
    <!-- Bootstrap CSS CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body style="background-image:url('https://i.pinimg.com/564x/a1/45/2a/a1452aef537a0fd6e4235d0af24d8f3c.jpg')">

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white text-center">
                    <h2>Kirish</h2>
                </div>
                <div class="card-body" style="background:#81d3e7">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-block">Kirish</button>
                        <a class="btn btn-primary d-grid gap-2 col-6 mx-auto" href="{% url 'users:register' %}" role="button" style="margin:10px">Akauntingiz mavjud emasmi?</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ro'yhatdan o'tish</title>
    <!-- Bootstrap CSS CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body style="background-image:url('https://i.pinimg.com/564x/a1/45/2a/a1452aef537a0fd6e4235d0af24d8f3c.jpg')">
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white text-center">
                    <h2>Ro'yhatdan o'tish</h2>
                </div>
                <div class="card-body" style="background:#81d3e7">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-block">Ro'yhatdan o'tish</button>
                        <a class="btn btn-primary d-grid gap-2 col-6 mx-auto" href="{% url 'users:login' %}" role="button" style="margin:10px">Akauntingiz mavjudmi?</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap JS, Popper.js, and jQuery CDN -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>